Hotfix/add pkg retries
SUSE/drbd-formula pull request #7
Opened 2019-11-13 12:14 UTC by arbulu89

The packages installation fails time to time, so the retries add robustness.
Besides that, the package `nfs-kernel-server` was not being installed together with the pattern making the cluster installation fail. I don't know if this is the best place to install this package.

2019-11-13 12:34 UTC, diegoakechi approved these changes
LGTM. I would say the correct location for the NFS packages installation would be on the NFS formula, but I saw that we already included the NFS formula installation also inside the DRBD formula too...

2019-11-13 13:31 UTC, arbulu89 commented
> LGTM. I would say the correct location for the NFS packages installation would be on the NFS formula, but I saw that we already included the NFS formula installation also inside the DRBD formula too...

Right not the `nfs-formula` is not installed if the `ha` pattern is not available. This PR fixes that but we might need to think if there is not a better place.

Actually, I don't think `nfs-formula` is available in obs..

2019-11-13 14:20 UTC, nick-wang requested changes

2019-11-13 14:20 UTC, nick-wang commented on drbd/packages.sls
> +      - nfs-kernel-server
I intend to not including `nfs` related things in drbd formula and leave the pure DRBD only things here. 
I think it is better to move it to HA/SAP/Terraform.
Also add the `state` here may incomplete when not use pattern plus `drbd.with_ha == true`. (the nfs-server is recommend in `nfs-formula`)

Sidenote: Though the vip in pillar is more like a HA thing, but it is also per DRBD resource parameter

2019-11-13 14:26 UTC, nick-wang commented
> LGTM. I would say the correct location for the NFS packages installation would be on the NFS formula, but I saw that we already included the NFS formula installation also inside the DRBD formula too...

The `nfs-formula` only installed when no patterns and HA package installed. Maybe it is also too much for `drbd-formula` in the packages, since it is just for `nfs_ready.sls`.

The `init.sls` is the minimal usage for the DRBD cluster.

2019-11-14 07:23 UTC, nick-wang commented on drbd/packages.sls
> +      - nfs-kernel-server
@arbulu89 I add the `nfs-kernel-server` to terraform `drbd_node`. Refer to https://github.com/SUSE/ha-sap-terraform-deployments/pull/239/commits/e28bc1e32ff50823cbd4dd3d008bdd978e112621

2019-11-14 07:24 UTC, nick-wang commented
@arbulu89 @diegoakechi Packages like `nfs-kernel-server` and `nfs-client` is built-in in SUMA image SLE15SP1... so i didn't meet this error.

I just add `nfs-kernel-server` in `drbd_node` of terraform project (https://github.com/SUSE/ha-sap-terraform-deployments/pull/239/commits/e28bc1e32ff50823cbd4dd3d008bdd978e112621) and succeed on testing against SAP SLE15SP1 image. I think it should not be a requirement in generic `packages.sls`, maybe `nfs_ready.sls` is a better place (also same for nfs-`formula` i added in  `packages.sls`).

2019-11-14 08:05 UTC, arbulu89 commented
@nick-wang Ok, I will revert the `nfs-kernel-server` installation. What about the retries?

2019-11-14 08:31 UTC, nick-wang commented
> @nick-wang Ok, I will revert the `nfs-kernel-server` installation. What about the retries?

Thanks for the help. The retry is good enhancement and look good.

2019-11-14 08:31 UTC, nick-wang approved these changes

2019-11-14 09:11 UTC, merged